version: '3'

services:
  app:
    image: jose2506/inteligencia:0.0.1-snapshot-latest
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      API_KEY: ${API_KEY}
      API_CHATGPT_HOST: ${API_CHATGPT_HOST}
      API_CHATGPT_KEY: ${API_CHATGPT_KEY}
      API_CHATGPT_URL: ${API_CHATGPT_URL}
