FROM openjdk:17
WORKDIR /app
COPY target/*.jar app.jar

ENV DATABASE_URL ${DATABASE_URL}
ENV DATABASE_USERNAME ${DATABASE_USERNAME}
ENV DATABASE_PASSWORD ${DATABASE_PASSWORD}
ENV API_KEY ${API_KEY}
ENV API_CHATGPT_HOST ${API_CHATGPT_HOST}
ENV API_CHATGPT_KEY ${API_CHATGPT_KEY}
ENV API_CHATGPT_URL ${API_CHATGPT_URL}


EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
